version: "3.8"

services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raffi_estoque
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend/latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/raffi_estoque
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - my-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend/latest
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
