server:
  port: 8080
spring:
  application:
    name: raffi-estoque
  datasource:
    url: jdbc:mysql://localhost:3306/raffi_estoque?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      format-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true