spring:
  application:
    name: raffi-estoque
  datasource:
    url: jdbc:mysql://localhost:3306/raffi_estoque?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true